//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserAssetMapping
    {
        public int AUAMID { get; set; }
        public Nullable<int> AppUserID { get; set; }
        public Nullable<int> AAMID { get; set; }
    }
}
