//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_wet_area_water_tightness_test_tran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assessment_wet_area_water_tightness_test_tran()
        {
            this.assessment_wet_area_water_tightness_test_tran_detail = new HashSet<assessment_wet_area_water_tightness_test_tran_detail>();
            this.assessment_wet_area_water_tightness_test_tran_detail_result = new HashSet<assessment_wet_area_water_tightness_test_tran_detail_result>();
        }
    
        public int AssessmentWAWTTID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string Block_Unit { get; set; }
        public string Drawing_Image { get; set; }
        public string Other_Result { get; set; }
        public int MobileAssessmentWAWTTID { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual assessment_project_master assessment_project_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_wet_area_water_tightness_test_tran_detail> assessment_wet_area_water_tightness_test_tran_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_wet_area_water_tightness_test_tran_detail_result> assessment_wet_area_water_tightness_test_tran_detail_result { get; set; }
    }
}
