//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_type_location_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assessment_type_location_master()
        {
            this.assessment_external_wall_trn = new HashSet<assessment_external_wall_trn>();
            this.assessment_external_works_trn = new HashSet<assessment_external_works_trn>();
            this.assessment_internal_finishes_trn = new HashSet<assessment_internal_finishes_trn>();
            this.assessment_roof_construction_trn = new HashSet<assessment_roof_construction_trn>();
            this.assessment_type_module_Process_master = new HashSet<assessment_type_module_Process_master>();
        }
    
        public int AssessmentTypeLocationID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public string AssessmentTypeLocationName { get; set; }
        public string AssessmentTypeLocationShortName { get; set; }
        public string AssessmentTypeLocationType { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_external_wall_trn> assessment_external_wall_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_external_works_trn> assessment_external_works_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_internal_finishes_trn> assessment_internal_finishes_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_roof_construction_trn> assessment_roof_construction_trn { get; set; }
        public virtual assessment_type_master assessment_type_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_type_module_Process_master> assessment_type_module_Process_master { get; set; }
    }
}
