//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_project_weightage_detail
    {
        public int ProjectWeightageDetailID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> AssessmentTypeModuleID { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public int RowNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual assessment_project_master assessment_project_master { get; set; }
        public virtual assessment_type_module_master assessment_type_module_master { get; set; }
    }
}
