//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_external_wall_trn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assessment_external_wall_trn()
        {
            this.assessment_external_wall_trn_detail = new HashSet<assessment_external_wall_trn_detail>();
        }
    
        public int AssessmentEWID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string Block_Unit { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Drawing_Image { get; set; }
        public int MobileAssessmentEWID { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual assessment_project_master assessment_project_master { get; set; }
        public virtual assessment_type_location_master assessment_type_location_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_external_wall_trn_detail> assessment_external_wall_trn_detail { get; set; }
    }
}
