//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_type_module_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assessment_type_module_master()
        {
            this.assessment_project_weightage_detail = new HashSet<assessment_project_weightage_detail>();
            this.assessment_type_module_Process_master = new HashSet<assessment_type_module_Process_master>();
            this.assessment_type_module_weightage = new HashSet<assessment_type_module_weightage>();
        }
    
        public int AssessmentTypeModuleID { get; set; }
        public Nullable<int> AssessmentTypeID { get; set; }
        public string AssessmentTypeModuleName { get; set; }
        public string AssessmentTypeModuleShortName { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public int NoOfRow { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_project_weightage_detail> assessment_project_weightage_detail { get; set; }
        public virtual assessment_type_master assessment_type_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_type_module_Process_master> assessment_type_module_Process_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_type_module_weightage> assessment_type_module_weightage { get; set; }
    }
}
