//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_field_window_water_tightness_test
    {
        public int AssessmentFWWTTID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string Block_Unit { get; set; }
        public int AssessmentWallID { get; set; }
        public int AssessmentWindowID { get; set; }
        public int AssessmentJointID { get; set; }
        public int AssessmentDirectionID { get; set; }
        public int AssessmentLeakID { get; set; }
        public string Result { get; set; }
        public string Drawing_Image { get; set; }
        public int MobileAssessmentFWWTTID { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual assessment_direction_master assessment_direction_master { get; set; }
        public virtual assessment_joint_master assessment_joint_master { get; set; }
        public virtual assessment_leak_master assessment_leak_master { get; set; }
        public virtual assessment_project_master assessment_project_master { get; set; }
        public virtual assessment_wall_master assessment_wall_master { get; set; }
        public virtual assessment_window_master assessment_window_master { get; set; }
    }
}
