//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_project_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assessment_project_master()
        {
            this.assessment_external_wall_trn = new HashSet<assessment_external_wall_trn>();
            this.assessment_external_works_trn = new HashSet<assessment_external_works_trn>();
            this.assessment_internal_finishes_trn = new HashSet<assessment_internal_finishes_trn>();
            this.assessment_project_assessors_detail = new HashSet<assessment_project_assessors_detail>();
            this.assessment_project_weightage_detail = new HashSet<assessment_project_weightage_detail>();
            this.assessment_roof_construction_trn = new HashSet<assessment_roof_construction_trn>();
            this.assessment_wet_area_water_tightness_test_tran = new HashSet<assessment_wet_area_water_tightness_test_tran>();
            this.assessment_field_window_water_tightness_test = new HashSet<assessment_field_window_water_tightness_test>();
        }
    
        public int ProjectID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Project_Name { get; set; }
        public string Project_ID { get; set; }
        public string Project_DocNo { get; set; }
        public string Developer_Name { get; set; }
        public string Contractor_Name { get; set; }
        public Nullable<System.DateTime> Assessment_StartOn { get; set; }
        public Nullable<System.DateTime> Assessment_EndOn { get; set; }
        public string Assessment_Dates { get; set; }
        public Nullable<int> DevelopmentTypeID { get; set; }
        public Nullable<decimal> ArchitecturalWorksWeightage { get; set; }
        public Nullable<decimal> MEWorksWeightage { get; set; }
        public Nullable<decimal> BuildQASScore { get; set; }
        public Nullable<decimal> MinimumCompliancePercentageThreshold { get; set; }
        public Nullable<int> Is_ExternalWallApplicable { get; set; }
        public Nullable<int> Is_ExternalWorksApplicable { get; set; }
        public Nullable<int> Is_RoofApplicable { get; set; }
        public Nullable<int> Is_FieldWindowWTTApplicable { get; set; }
        public Nullable<int> Is_WetAreaWTTApplicable { get; set; }
        public string FieldWindowWTT_Contractor_Name { get; set; }
        public string FieldWindowWTT_Witness_Name { get; set; }
        public string WetAreaWTT_Contractor_Name { get; set; }
        public string WetAreaWTT_Witness_Name { get; set; }
        public Nullable<int> Is_Completed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual assessment_development_type_master assessment_development_type_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_external_wall_trn> assessment_external_wall_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_external_works_trn> assessment_external_works_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_internal_finishes_trn> assessment_internal_finishes_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_project_assessors_detail> assessment_project_assessors_detail { get; set; }
        public virtual company_master company_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_project_weightage_detail> assessment_project_weightage_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_roof_construction_trn> assessment_roof_construction_trn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_wet_area_water_tightness_test_tran> assessment_wet_area_water_tightness_test_tran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assessment_field_window_water_tightness_test> assessment_field_window_water_tightness_test { get; set; }
    }
}
