//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment_type_module_weightage
    {
        public int AssessmentTypeModuleWeightageID { get; set; }
        public Nullable<int> DevelopmentTypeID { get; set; }
        public Nullable<int> AssessmentTypeModuleID { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual assessment_development_type_master assessment_development_type_master { get; set; }
        public virtual assessment_type_module_master assessment_type_module_master { get; set; }
    }
}
