//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuildInspectEntities : DbContext
    {
        public BuildInspectEntities()
            : base("name=BuildInspectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<AppUserAssetMapping> AppUserAssetMappings { get; set; }
        public virtual DbSet<AppUserGroup> AppUserGroups { get; set; }
        public virtual DbSet<assessment_development_type_master> assessment_development_type_master { get; set; }
        public virtual DbSet<assessment_direction_master> assessment_direction_master { get; set; }
        public virtual DbSet<assessment_external_wall_trn> assessment_external_wall_trn { get; set; }
        public virtual DbSet<assessment_external_wall_trn_detail> assessment_external_wall_trn_detail { get; set; }
        public virtual DbSet<assessment_external_works_trn> assessment_external_works_trn { get; set; }
        public virtual DbSet<assessment_external_works_trn_detail> assessment_external_works_trn_detail { get; set; }
        public virtual DbSet<assessment_internal_finishes_trn> assessment_internal_finishes_trn { get; set; }
        public virtual DbSet<assessment_internal_finishes_trn_detail> assessment_internal_finishes_trn_detail { get; set; }
        public virtual DbSet<assessment_joint_master> assessment_joint_master { get; set; }
        public virtual DbSet<assessment_leak_master> assessment_leak_master { get; set; }
        public virtual DbSet<assessment_project_assessors_detail> assessment_project_assessors_detail { get; set; }
        public virtual DbSet<assessment_project_master> assessment_project_master { get; set; }
        public virtual DbSet<assessment_project_weightage_detail> assessment_project_weightage_detail { get; set; }
        public virtual DbSet<assessment_roof_construction_trn> assessment_roof_construction_trn { get; set; }
        public virtual DbSet<assessment_roof_construction_trn_detail> assessment_roof_construction_trn_detail { get; set; }
        public virtual DbSet<assessment_type_location_master> assessment_type_location_master { get; set; }
        public virtual DbSet<assessment_type_master> assessment_type_master { get; set; }
        public virtual DbSet<assessment_type_module_master> assessment_type_module_master { get; set; }
        public virtual DbSet<assessment_type_module_Process_master> assessment_type_module_Process_master { get; set; }
        public virtual DbSet<assessment_type_module_weightage> assessment_type_module_weightage { get; set; }
        public virtual DbSet<assessment_wall_master> assessment_wall_master { get; set; }
        public virtual DbSet<assessment_wet_area_water_tightness_test_tran_detail> assessment_wet_area_water_tightness_test_tran_detail { get; set; }
        public virtual DbSet<assessment_window_master> assessment_window_master { get; set; }
        public virtual DbSet<assessors_master> assessors_master { get; set; }
        public virtual DbSet<company_master> company_master { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<qcinspection_block_master> qcinspection_block_master { get; set; }
        public virtual DbSet<qcinspection_defect_files> qcinspection_defect_files { get; set; }
        public virtual DbSet<qcinspection_defect_type_master> qcinspection_defect_type_master { get; set; }
        public virtual DbSet<qcinspection_level_master> qcinspection_level_master { get; set; }
        public virtual DbSet<qcinspection_project_files> qcinspection_project_files { get; set; }
        public virtual DbSet<qcinspection_project_PM_detail> qcinspection_project_PM_detail { get; set; }
        public virtual DbSet<qcinspection_project_rfwi_drawing_reference_files> qcinspection_project_rfwi_drawing_reference_files { get; set; }
        public virtual DbSet<qcinspection_project_Supervisor_detail> qcinspection_project_Supervisor_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_form_general_checklist_detail> qcinspection_rfwi_form_general_checklist_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_form_location_detail> qcinspection_rfwi_form_location_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_form_trade_detailed_checklist_detail> qcinspection_rfwi_form_trade_detailed_checklist_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_form_trade_item_detail> qcinspection_rfwi_form_trade_item_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_general_checklist_master> qcinspection_rfwi_general_checklist_master { get; set; }
        public virtual DbSet<qcinspection_rfwi_trade_detailed_checklist_detail> qcinspection_rfwi_trade_detailed_checklist_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_trade_item_detail> qcinspection_rfwi_trade_item_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_trade_master> qcinspection_rfwi_trade_master { get; set; }
        public virtual DbSet<qcinspection_subcontractor_master> qcinspection_subcontractor_master { get; set; }
        public virtual DbSet<qcinspection_subcontractor_trade_detail> qcinspection_subcontractor_trade_detail { get; set; }
        public virtual DbSet<qcinspection_trade_master> qcinspection_trade_master { get; set; }
        public virtual DbSet<qcinspection_unit_master> qcinspection_unit_master { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<assessment_wet_area_water_tightness_test_result_master> assessment_wet_area_water_tightness_test_result_master { get; set; }
        public virtual DbSet<assessment_wet_area_water_tightness_test_tran_detail_result> assessment_wet_area_water_tightness_test_tran_detail_result { get; set; }
        public virtual DbSet<qcinspection_project_MEInspector_detail> qcinspection_project_MEInspector_detail { get; set; }
        public virtual DbSet<qcinspection_project_OtherInspector_detail> qcinspection_project_OtherInspector_detail { get; set; }
        public virtual DbSet<qcinspection_project_StructureInspector_detail> qcinspection_project_StructureInspector_detail { get; set; }
        public virtual DbSet<qcinspection_rfwi_form> qcinspection_rfwi_form { get; set; }
        public virtual DbSet<qcinspection_project_master> qcinspection_project_master { get; set; }
        public virtual DbSet<qcinspection_defect_form> qcinspection_defect_form { get; set; }
        public virtual DbSet<assessment_wet_area_water_tightness_test_tran> assessment_wet_area_water_tightness_test_tran { get; set; }
        public virtual DbSet<assessment_field_window_water_tightness_test> assessment_field_window_water_tightness_test { get; set; }
    }
}
