//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_subcontractor_trade_detail
    {
        public int SubcontractorTradeID { get; set; }
        public int SubcontractorID { get; set; }
        public int TradeID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual qcinspection_subcontractor_master qcinspection_subcontractor_master { get; set; }
        public virtual qcinspection_trade_master qcinspection_trade_master { get; set; }
    }
}
