//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_defect_form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qcinspection_defect_form()
        {
            this.qcinspection_defect_files = new HashSet<qcinspection_defect_files>();
        }
    
        public int QCInspectionDefectID { get; set; }
        public string QCInspectionDefectNo { get; set; }
        public int ProjectID { get; set; }
        public int UnitID { get; set; }
        public int TradeID { get; set; }
        public int DefectTypeID { get; set; }
        public string DefectRemarks { get; set; }
        public int SubcontractorID { get; set; }
        public int ProjectManagerID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedRemarks { get; set; }
        public Nullable<int> ReDoBy { get; set; }
        public Nullable<System.DateTime> ReDoDate { get; set; }
        public string ReDoRemarks { get; set; }
        public Nullable<int> ReDoDoneBy { get; set; }
        public Nullable<System.DateTime> ReDoDoneDate { get; set; }
        public string ReDoDoneRemarks { get; set; }
        public Nullable<int> RectificationBy { get; set; }
        public Nullable<System.DateTime> RectificationDate { get; set; }
        public string RectificationRemarks { get; set; }
        public string RectificationSignature { get; set; }
        public Nullable<int> ReworkBy { get; set; }
        public Nullable<System.DateTime> ReworkDate { get; set; }
        public string ReworkRemarks { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedRemarks { get; set; }
        public string CompletedSignature { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<int> MobileQCInspectionDefectID { get; set; }
        public string BatchID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_defect_files> qcinspection_defect_files { get; set; }
        public virtual qcinspection_defect_type_master qcinspection_defect_type_master { get; set; }
        public virtual qcinspection_subcontractor_master qcinspection_subcontractor_master { get; set; }
        public virtual qcinspection_trade_master qcinspection_trade_master { get; set; }
        public virtual qcinspection_unit_master qcinspection_unit_master { get; set; }
        public virtual user user { get; set; }
    }
}
