//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_project_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qcinspection_project_master()
        {
            this.qcinspection_block_master = new HashSet<qcinspection_block_master>();
            this.qcinspection_project_files = new HashSet<qcinspection_project_files>();
            this.qcinspection_project_MEInspector_detail = new HashSet<qcinspection_project_MEInspector_detail>();
            this.qcinspection_project_OtherInspector_detail = new HashSet<qcinspection_project_OtherInspector_detail>();
            this.qcinspection_project_PM_detail = new HashSet<qcinspection_project_PM_detail>();
            this.qcinspection_project_rfwi_drawing_reference_files = new HashSet<qcinspection_project_rfwi_drawing_reference_files>();
            this.qcinspection_project_StructureInspector_detail = new HashSet<qcinspection_project_StructureInspector_detail>();
            this.qcinspection_project_Supervisor_detail = new HashSet<qcinspection_project_Supervisor_detail>();
            this.qcinspection_rfwi_form = new HashSet<qcinspection_rfwi_form>();
        }
    
        public int ProjectID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Project_Name { get; set; }
        public string Project_ID { get; set; }
        public Nullable<System.DateTime> StartOn { get; set; }
        public Nullable<System.DateTime> EndOn { get; set; }
        public Nullable<int> Is_Completed { get; set; }
        public Nullable<int> ProjectManagerID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual company_master company_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_block_master> qcinspection_block_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_files> qcinspection_project_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_MEInspector_detail> qcinspection_project_MEInspector_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_OtherInspector_detail> qcinspection_project_OtherInspector_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_PM_detail> qcinspection_project_PM_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_rfwi_drawing_reference_files> qcinspection_project_rfwi_drawing_reference_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_StructureInspector_detail> qcinspection_project_StructureInspector_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_Supervisor_detail> qcinspection_project_Supervisor_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form> qcinspection_rfwi_form { get; set; }
    }
}
