//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_rfwi_trade_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qcinspection_rfwi_trade_master()
        {
            this.qcinspection_rfwi_trade_detailed_checklist_detail = new HashSet<qcinspection_rfwi_trade_detailed_checklist_detail>();
            this.qcinspection_rfwi_trade_item_detail = new HashSet<qcinspection_rfwi_trade_item_detail>();
            this.qcinspection_rfwi_form = new HashSet<qcinspection_rfwi_form>();
        }
    
        public int TradeID { get; set; }
        public string TradeName { get; set; }
        public int OrderBy { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_trade_detailed_checklist_detail> qcinspection_rfwi_trade_detailed_checklist_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_trade_item_detail> qcinspection_rfwi_trade_item_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form> qcinspection_rfwi_form { get; set; }
    }
}
