//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_unit_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qcinspection_unit_master()
        {
            this.qcinspection_rfwi_form_location_detail = new HashSet<qcinspection_rfwi_form_location_detail>();
            this.qcinspection_defect_form = new HashSet<qcinspection_defect_form>();
        }
    
        public int UnitID { get; set; }
        public int LevelID { get; set; }
        public string UnitName { get; set; }
        public int OrderBy { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual qcinspection_level_master qcinspection_level_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form_location_detail> qcinspection_rfwi_form_location_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_defect_form> qcinspection_defect_form { get; set; }
    }
}
