//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_project_rfwi_drawing_reference_files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qcinspection_project_rfwi_drawing_reference_files()
        {
            this.qcinspection_rfwi_form_location_detail = new HashSet<qcinspection_rfwi_form_location_detail>();
        }
    
        public int QCInspectionDrawingReferenceFileID { get; set; }
        public int ProjectID { get; set; }
        public string FileCaption { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form_location_detail> qcinspection_rfwi_form_location_detail { get; set; }
        public virtual qcinspection_project_master qcinspection_project_master { get; set; }
    }
}
