//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class qcinspection_rfwi_form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qcinspection_rfwi_form()
        {
            this.qcinspection_rfwi_form_general_checklist_detail = new HashSet<qcinspection_rfwi_form_general_checklist_detail>();
            this.qcinspection_rfwi_form_location_detail = new HashSet<qcinspection_rfwi_form_location_detail>();
            this.qcinspection_rfwi_form_trade_detailed_checklist_detail = new HashSet<qcinspection_rfwi_form_trade_detailed_checklist_detail>();
            this.qcinspection_rfwi_form_trade_item_detail = new HashSet<qcinspection_rfwi_form_trade_item_detail>();
        }
    
        public int QCInspectionRFWIFormID { get; set; }
        public string QCInspectionRFWINo { get; set; }
        public int ProjectID { get; set; }
        public int TradeID { get; set; }
        public Nullable<int> RequestBy { get; set; }
        public Nullable<System.DateTime> RequestOn { get; set; }
        public string RequestSignature { get; set; }
        public string NotiicationReceivedByName { get; set; }
        public string NotiicationReceivedSignature { get; set; }
        public Nullable<System.DateTime> NotiicationReceivedOn { get; set; }
        public byte InspectionNo { get; set; }
        public Nullable<System.DateTime> InspectionOn { get; set; }
        public Nullable<System.TimeSpan> InspectionStartOn { get; set; }
        public Nullable<System.TimeSpan> InspectionEndOn { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public string RequestFor { get; set; }
        public string ItemOthers { get; set; }
        public string DetailedCheckListOthers { get; set; }
        public bool OtherTradeClearance_Structure { get; set; }
        public Nullable<int> OtherTradeClearance_StructureBy { get; set; }
        public string OtherTradeClearance_StructureSignature { get; set; }
        public Nullable<System.DateTime> OtherTradeClearance_StructureOn { get; set; }
        public bool OtherTradeClearance_MandE { get; set; }
        public Nullable<int> OtherTradeClearance_MandEBy { get; set; }
        public string OtherTradeClearance_MandESignature { get; set; }
        public Nullable<System.DateTime> OtherTradeClearance_MandEOn { get; set; }
        public bool OtherTradeClearance_Other { get; set; }
        public Nullable<int> OtherTradeClearance_OtherBy { get; set; }
        public string OtherTradeClearance_OtherSignature { get; set; }
        public Nullable<System.DateTime> OtherTradeClearance_OtherOn { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedRemarks { get; set; }
        public string CompletedSignature { get; set; }
        public int ReInspectionFormID { get; set; }
        public string Status { get; set; }
        public Nullable<int> MobileQCInspectionRFWIFormID { get; set; }
        public string BatchID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form_general_checklist_detail> qcinspection_rfwi_form_general_checklist_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form_location_detail> qcinspection_rfwi_form_location_detail { get; set; }
        public virtual qcinspection_rfwi_trade_master qcinspection_rfwi_trade_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form_trade_detailed_checklist_detail> qcinspection_rfwi_form_trade_detailed_checklist_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form_trade_item_detail> qcinspection_rfwi_form_trade_item_detail { get; set; }
        public virtual user user { get; set; }
        public virtual qcinspection_project_master qcinspection_project_master { get; set; }
    }
}
