//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.qcinspection_project_PM_detail = new HashSet<qcinspection_project_PM_detail>();
            this.qcinspection_project_Supervisor_detail = new HashSet<qcinspection_project_Supervisor_detail>();
            this.qcinspection_project_MEInspector_detail = new HashSet<qcinspection_project_MEInspector_detail>();
            this.qcinspection_project_OtherInspector_detail = new HashSet<qcinspection_project_OtherInspector_detail>();
            this.qcinspection_project_StructureInspector_detail = new HashSet<qcinspection_project_StructureInspector_detail>();
            this.qcinspection_rfwi_form = new HashSet<qcinspection_rfwi_form>();
            this.qcinspection_defect_form = new HashSet<qcinspection_defect_form>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string UID { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string ServiceType { get; set; }
        public string Zone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public Nullable<int> TeamLead_ID { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<int> ProjMngr_ID { get; set; }
        public Nullable<int> SubCon_ID { get; set; }
        public Nullable<int> Supvsr_ID { get; set; }
        public Nullable<int> Assessor_ID { get; set; }
        public string DeviceID { get; set; }
    
        public virtual company_master company_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_PM_detail> qcinspection_project_PM_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_Supervisor_detail> qcinspection_project_Supervisor_detail { get; set; }
        public virtual usergroup usergroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_MEInspector_detail> qcinspection_project_MEInspector_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_OtherInspector_detail> qcinspection_project_OtherInspector_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_project_StructureInspector_detail> qcinspection_project_StructureInspector_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_rfwi_form> qcinspection_rfwi_form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qcinspection_defect_form> qcinspection_defect_form { get; set; }
    }
}
